.TH GOOGLE "1" "August 2015" "FIREFOX & CHROME UTILS" "Google Commands"
.SH NAME
Google \- search on the internet
.SH SYNOPSIS
.B firefox google.com
.TP
.B google-chrome google.com
.SH DESCRIPTION
.PP
Search your mandatory informations via your webbrowser on google. It will provide you informations on how to do stuff.
.B IT IS REALLY IMPORTANT FOR YOU TO KNOW HOW TO USE IT..
.TP
\fBQuotes:\fR
Don't be stupid, use quotes to find a precise sentence in a page in the exact same order, like
.B \(aqI lost the Game\(aq
instead of
.B I lost the Game
, like that you will find where someone lost and you will lose too.
.TP
\fBMinus:\fR
If you are not an
.B absolute retard
you will have noticed that using a
.B minus
excludes words from the search. Therefore typing
.B \(aqCarmen Electra -porn\(aq
will lead you to find what Carmen Electra did that is not porn (which is actually
.B stupid
, because she's only good at doing porn).
.TP
\fBColon:\fR
Jackasses
.B(what you definitely are)
search \(aqfacebook François hollande\(aq, less idiotic people tend to search for
.B \(aqFrançois Hollande site:facebook.com\(aq.
.TP
\fBLinks:\fR
If you want to
.B find a page that links to another
for whatever your fucking reason is, juste add
.B \(aqlinks:your_website.com\(aq
in your search.
.TP
\fBAsterisk:\fR
If you are a retard and forgot something in a specific sentence you are searching, just put it in quotes with a fucking
.B asterisk
 at the place of what you idiot forgot.
.TP
\fBRelation:\fR
If you want to find a webpage that is related to another one, just add
.B \(aqrelated:the_website.com\(aq
, was it that hard?
.TP
\fBDo not use useless words:\fR
Haven't you understood that the words \(aqhow, i, the\(aq and such are located in every fucking website?
.TP
\fBUse words that actually have a sense in what you are searching:\fR
If you want to search \(aqtroobleshoot driver problems ubuntu\(aq do not search \(aqhow to install drivers in Ubuntu\(aq, you morron.
.SH SEE ALSO
The full documentation for
.B Google
is maintained as a
.B Webinfo.
If programs are properly installed at your site, the command
.IP
.B firefox \(aqhttp://lmgtfy.com/?q=how+to+use+google+properly\(aq
.TP
should give you access to the complete manual.
.PP

.SH AUTHOR
.B Created by Paul Montague
.TP
.B Update by Maxime Bruguet
