#! /bin/bash

## script

files="./.files"
dir_tmp="/tmp/install"

login=$1

## fake install ?

fake=0

## colors

ESC="\033["
C_RED=$ESC"0;31m"
C_YELLOW=$ESC"0;33m"
C_BWHITE=$ESC"1;37m"
C_RST=$ESC"0m"


function usage
{
	echo
	echo "Usage: $0 <prenom.nom@epitech.eu>"
	echo
	echo "<prenom.nom@epitech.eu> : Votre login Epitech"
	echo
}

if test $UID -eq 0; then
	echo ">> Ne pas lancer ce script en tant que sudo <<"
	usage
	exit 1
fi
if test -z "$login"; then
	usage
	exit 1
fi

function script_init
{
	rm -rf $dir_tmp
	mkdir $dir_tmp
}

function line
{
	cols=$(tput cols)
	char=$1
	color=$2

	if test "$color" != ""; then
		echo -ne $color
	fi

	for i in $(eval echo "{1..$cols}"); do
		echo -n $char
	done
	echo

	if test "$color" != ""; then
		echo -ne $C_RST
	fi
}

function script_header
{

	color=$2
	if test "$color" = ""; then
		color=$C_RED
	fi

	echo -ne $color
	line "-"
	echo "##> "$1
	line "-"
	echo -ne $C_RST
}

function handle_error
{
	result=$1
	if test $result -eq 0; then
		return
	else
		line "#" $C_RED
		line "#" $C_YELLOW
		echo -en $C_RED"[Erreur]"$C_RST" lors de l'installation, voulez-vous arreter le script ? [O/n]  "
		read stop_script
		case $stop_script in
			n|N)	return;;
			*)		exit 1;;
		esac
	fi
}

function sys_upgrade
{
	if test $fake -eq 1; then
		echo "Upgrade system"
		return
	fi
	#TODO: handle other OS
	sudo apt-get update
	handle_error $?
	sudo apt-get upgrade
	handle_error $?
}

function sys_install
{
	if test $fake -eq 1; then
		echo "Installing "$1
		return
	fi
	#TODO: handle other OS
	sudo apt-get install $1
	handle_error $?
}

function script_install
{
	if test $fake -eq 1; then
		echo "Installing "$1
		return
	fi
	sudo cp $files/$1 /usr/bin/$1
	handle_error $?
	sudo chmod 755 /usr/bin/$1
	handle_error $?
}

function setup_emacs
{
	if test $fake -eq 1; then
		echo "Setup emacs"
		#return
	fi
	emacs_tmp=$dir_tmp/.emacs.d

	cp -r $files/.emacs.d $dir_tmp

	sed 's/(getenv "USER")/"'$login'"/g' $emacs_tmp/std_comment.el > $emacs_tmp/std_comment.el.tmp
	mv $emacs_tmp/std_comment.el.tmp $emacs_tmp/std_comment.el

	cp $files/.emacs /home/$USER/
	chmod +rw /home/$USER/.emacs

	cp -r $emacs_tmp /home/$USER/
	chmod +rw /home/$USER/.emacs.d
	chmod +rw /home/$USER/.emacs.d/*
}

script_init

script_header "INSTALLATION DE BLIH"
script_install blih

script_header "MISE À JOUR DES SOURCES ET DU SYSTÈME"
sys_upgrade

script_header "INSTALLATION DE EMACS ET DU SYSTÈME DE HEADERS EPITECH"
sys_install emacs
setup_emacs

script_header "INSTALLATION DE BUILD-ESSENTIAL POUR LA COMPILATION"
sys_install build-essential

script_header "INSTALLATION DE VALGRIND"
sys_install valgrind

script_header "INSTALLATION DE OCAML"
sys_install ocaml

script_header "INSTALLATION DE LA LIBNCURSES"
sys_install libncurses5

script_header "INSTALLATION DE CURL"
sys_install curl

script_header "INSTALLATION DE GIT, GENERATION DE LA CLE SSH ET UPLOAD SUR SERVEUR EPITECH"

script_header "GIT" $C_YELLOW
sys_install git

script_header "CLE SSH, LEAVE EVERYTHING AS DEFAULT" $C_YELLOW
ssh-keygen
handle_error $?

script_header "BLIH SSH UPLOAD" $C_YELLOW
echo "mot de passe UNIX (bocal, pour blih)"
blih -u "$1" sshkey upload /home/$USER/.ssh/id_rsa.pub
handle_error $?

script_header "INSTALLATION ET CONFIGURATION DE ZSH ET OH MY ZSH"

script_header "ZSH" $C_YELLOW
sys_install zsh

script_header "OH-MY-ZSH" $C_YELLOW
curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
#no error check here: remote install.sh has a chsh error
chsh $USER -s /usr/bin/zsh
handle_error $?
echo "alias blih='blih -u $1'" >> /home/$USER/.zshrc
echo "alias ns_auth='ns_auth -u $1'" >> /home/$USER/.zshrc

script_header "INSTALLATION DU MAN DE GOOGLE"
sudo cp $files/google.1 /usr/share/man/man1/google.1
handle_error $?

script_header "INSTALLATION DE TERMINATOR"
sys_install terminator

script_header "INSTALLATION DES OUTILS COMPLEMENTAIRES"
sys_install tree
sys_install filezilla

script_header "CHANGEMENT DES DROITS (-) SUR POWEROFF ET REBOOT"
sudo chmod +s /sbin/poweroff
handle_error $?
sudo chmod +s /sbin/reboot
handle_error $?

script_header "EFFACEMENT DES FICHIERS D'INSTALLATION"
rm -rvf ../installation

script_header "VOTRE OS EST PRÊT POUR EPITECH" $C_BWHITE

sudo -k
